// Auto-generated by scripts/generate-remote-types.mjs — do not edit.
// Remotes: install the host-remote-types package (npm or git) and add /// <reference types="host-remote-types" />

declare module 'host/Header' {
  export * from './dist-types/components/Header'
}

declare module 'host/models/Link.model' {
  export * from './dist-types/models/Link.model'
}
